[package]
name = "sbert"
version = "0.1.0"
authors = ["Chady Dimachkie <cpcdoy@gmail.com>"]
edition = "2018"
description = "Rust implementation of Sentence Bert (SBert)"
repository = "https://github.com/cpcdoy/rust-sbert"
keywords = ["nlp", "embedding", "sentence-embedding", "bert", "sbert", "transformers"]
license = "Apache-2.0"
readme = "README.md"
include = [
    "src/",
    "Cargo.toml",
]

[[test]]
name = "sbert_test"
path = "tests/test_sbert.rs"

[[bench]]
name = "sbert_bench"
path = "benches/bench_sbert.rs"
harness = false

[dev-dependencies]
criterion = "0.3"

[dependencies]
failure = "0.1"
rust_tokenizers = "2.0"
tokenizers = "0.10.1"
tch = "0.1.7"
thiserror = "1.0"
rust-bert = "0.7"
serde = "1.0"
strum = "0.18"
strum_macros = "0.18"
prost = "0.6"
libmath = "0.2"
rand = "0.7"
torch-sys = "0.1.7"
crossbeam = "0.3"