name: Rust

on:
  push:
    branches: [ "master", "test" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install gcc-multilib
      run: sudo apt-get update && sudo apt-get install -y gcc-multilib
    - name: Install libtorch
      run: |
        wget https://download.pytorch.org/libtorch/cpu/libtorch-shared-with-deps-2.0.1%2Bcpu.zip
        unzip libtorch-shared-with-deps-2.0.1+cpu.zip
        mv libtorch /opt/
        echo "libtorch dir"
        ls -la /opt/libtorch
        export LD_LIBRARY_PATH=/opt/libtorch/lib:$LD_LIBRARY_PATH
      shell: bash
    - name: Set LIBTORCH environment variable
      run: echo "LIBTORCH=/opt/libtorch" >> $GITHUB_ENV
    - name: Set LIBTORCH_INCLUDE environment variable
      run: echo "LIBTORCH_INCLUDE=/opt/libtorch" >> $GITHUB_ENV
    - name: Set LIBTORCH_LIB environment variable
      run: echo "LIBTORCH_LIB=/opt/libtorch" >> $GITHUB_ENV
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
